# Use a lightweight Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies (needed for psycopg2 + pyarrow)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy project files..
COPY . /app/

# Install Python dependencies
RUN pip install uv pandas pyarrow sqlalchemy requests click psycopg2 tqdm requests


# Default command (can be overridden)
ENTRYPOINT ["python"]